- name: Deploy Pods on Docker Container
  hosts: all
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Remove existing container (if exists)
      shell: docker rm -f {{ containerName }}
      ignore_errors: true

    - name: Run Docker container
      shell: docker run -d --name {{ containerName }} -p {{ httpPort }}:{{ httpPort }} {{ dockerImageTag }}

    - name: Show running containers
      command: docker ps
      register: docker_output

    - debug:
        var: docker_output.stdout
